import { COMPONENTS, constraintsOf, type FieldSpec, type FormSpec } from "./spec.js"

/**
 * Spec in, React out.
 *
 * Every hard decision lives here rather than in the model: which schema
 * validates which field, that money is an integer, that a formatting option
 * has to reach the schema as well as the component. The generator is
 * deterministic and tested, so those decisions are made once and correctly.
 */

/** Render a JS value into source. */
function lit(v: unknown): string {
  if (typeof v === "string") return JSON.stringify(v)
  if (typeof v === "number" || typeof v === "boolean") return String(v)
  if (Array.isArray(v)) return `[${v.map(lit).join(", ")}]`
  if (v && typeof v === "object") {
    return `{ ${Object.entries(v).map(([k, x]) => `${k}: ${lit(x)}`).join(", ")} }`
  }
  return "undefined"
}

/** A JSX attribute. Strings stay quoted; everything else goes in braces. */
function attr(key: string, value: unknown): string {
  if (value === true) return key
  if (value === false || value === undefined || value === null) return ""
  if (typeof value === "string") return `${key}=${JSON.stringify(value)}`
  return `${key}={${lit(value)}}`
}

function presentationAttrs(field: FieldSpec): string[] {
  const out: string[] = []
  for (const [key, value] of Object.entries(field)) {
    if (key === "type" || key === "name") continue
    const a = attr(key, value)
    if (a) out.push(a)
  }
  return out
}

function schemaCall(field: FieldSpec): string {
  const comp = COMPONENTS[field.type]
  const constraints = constraintsOf(field)
  const entries = Object.entries(constraints)
  if (!entries.length) return `${comp.schema}()`
  return `${comp.schema}({ ${entries.map(([k, v]) => `${k}: ${lit(v)}`).join(", ")} })`
}

function usedComponents(spec: FormSpec) {
  const seen = new Map<string, ReturnType<typeof typeOf>>()
  for (const f of spec.fields) seen.set(f.type, typeOf(f))
  return [...seen.values()]
}

function typeOf(f: FieldSpec) {
  return COMPONENTS[f.type]
}

/* ------------------------------------------------------------------ *
 * react-hook-form + Zod
 * ------------------------------------------------------------------ */

function renderRhf(spec: FormSpec): string {
  const comps = usedComponents(spec)

  const imports = [
    `import { Controller, useForm } from "react-hook-form"`,
    `import { zodResolver } from "@hookform/resolvers/zod"`,
    `import { z } from "zod"`,
    ``,
    ...comps.flatMap((c) => [
      `import { ${c.component} } from "${c.pkg}"`,
      `import { ${c.schema} } from "${c.pkg}/schema"`,
    ]),
  ].join("\n")

  const schema = [
    `const schema = z.object({`,
    ...spec.fields.map((f) => `  ${f.name}: ${schemaCall(f)},`),
    `})`,
  ].join("\n")

  const defaults = spec.fields
    .map((f) => {
      const t = COMPONENTS[f.type]
      const value = t.tsType === "number" ? "0" : t.tsType === "object" ? `{ text: "", ids: [] }` : `""`
      return `      ${f.name}: ${value},`
    })
    .join("\n")

  const fields = spec.fields
    .map((f) => {
      const comp = COMPONENTS[f.type]
      const attrs = presentationAttrs(f)
      const spread = attrs.length ? `\n            ${attrs.join("\n            ")}` : ""
      return `      <Controller
        name="${f.name}"
        control={control}
        render={({ field, fieldState }) => (
          <${comp.component}${spread}
            {...field}
            aria-invalid={fieldState.invalid}
          />
        )}
      />`
    })
    .join("\n\n")

  return `${imports}

${schema}

export type ${spec.name}Values = z.infer<typeof schema>

/**
 * Generated by \`npx inputcn generate\`. Safe to edit.
 *
 * Each field emits its canonical value, never the formatted string on screen:
${spec.fields.map((f) => ` *   ${f.name} — ${COMPONENTS[f.type].emits}`).join("\n")}
 */
export function ${spec.name}({
  onSubmit,
}: {
  onSubmit: (values: ${spec.name}Values) => void
}) {
  const { control, handleSubmit } = useForm<${spec.name}Values>({
    resolver: zodResolver(schema),
    defaultValues: {
${defaults}
    },
  })

  return (
    <form onSubmit={handleSubmit(onSubmit)} noValidate>
${fields}

      <button type="submit">${spec.submitLabel ?? "Submit"}</button>
    </form>
  )
}
`
}

/* ------------------------------------------------------------------ *
 * No form library — constraint props and native FormData
 * ------------------------------------------------------------------ */

function renderStandalone(spec: FormSpec): string {
  const comps = usedComponents(spec)

  const imports = comps.map((c) => `import { ${c.component} } from "${c.pkg}"`).join("\n")

  const fields = spec.fields
    .map((f) => {
      const comp = COMPONENTS[f.type]
      const attrs = [`name="${f.name}"`, ...presentationAttrs(f)]
      return `      <${comp.component}\n        ${attrs.join("\n        ")}\n      />`
    })
    .join("\n\n")

  const reads = spec.fields
    .map((f) => {
      const comp = COMPONENTS[f.type]
      const read =
        comp.tsType === "number"
          ? `Number(data.get("${f.name}"))`
          : `data.get("${f.name}")`
      return `  const ${f.name} = ${read} // ${comp.emits}`
    })
    .join("\n")

  return `${imports}

/**
 * Generated by \`npx inputcn generate\`. Safe to edit.
 *
 * No form library. Every rule is a prop, and the fields validate themselves —
 * silent until the first blur, clearing the moment the value becomes valid.
 *
 * Each component also renders a hidden input carrying its canonical value, so
 * this works unchanged as a Server Action with no client component:
 *
${reads
  .split("\n")
  .map((l) => ` * ${l.trim()}`)
  .join("\n")}
 */
export function ${spec.name}({
  action,
}: {
  action: (data: FormData) => void
}) {
  return (
    <form action={action} noValidate>
${fields}

      <button type="submit">${spec.submitLabel ?? "Submit"}</button>
    </form>
  )
}
`
}

export function generate(spec: FormSpec): string {
  return spec.form === "none" ? renderStandalone(spec) : renderRhf(spec)
}

/** The packages a generated file needs installed. */
export function dependencies(spec: FormSpec): string[] {
  const comps = usedComponents(spec)
  const base = comps.map((c) => c.pkg)
  return spec.form === "none"
    ? base
    : [...base, "react-hook-form", "@hookform/resolvers", "zod"]
}

/** The shadcn commands that copy the component sources in. */
export function installCommands(spec: FormSpec, site: string): string[] {
  return usedComponents(spec).map((c) => `npx shadcn@latest add ${site}/r/${c.slug}.json`)
}
